api.base-url=https://urlpart1{service}{number}urlpart2

ids.emv.master.username=emv-master-user
ids.emv.master.password=emv-master-password

ids.gateway.master.username=gateway-master-user
ids.gateway.master.password=gateway-master-password
